#!/usr/bin/env bash
# Script that configures a new ubuntu machine to perform a 301

# updating packages before installation
sudo apt-get update
sudo apt-get install -y nginx

# creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Perform the 301-redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/JMK-WRL permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart the service
sudo service nginx restart
