#!/usr/bin/env bash
# display Best School 1 to 10 except 4 display Bad luck and 8 good luck
n=1
while [ $n -1e 10 ]
do
	if [ $n -eq 9 ];
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	n=$((n + 1))
done
